[2024-08-25T19:29:01.158+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-25T19:29:01.180+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_kubernetes_workflow_v2.task-1 scheduled__2024-08-25T19:23:00+00:00 [queued]>
[2024-08-25T19:29:01.190+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_kubernetes_workflow_v2.task-1 scheduled__2024-08-25T19:23:00+00:00 [queued]>
[2024-08-25T19:29:01.191+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-08-25T19:29:01.207+0000] {taskinstance.py:2327} INFO - Executing <Task(KubernetesPodOperator): task-1> on 2024-08-25 19:23:00+00:00
[2024-08-25T19:29:01.218+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2108) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T19:29:01.220+0000] {standard_task_runner.py:63} INFO - Started process 2112 to run task
[2024-08-25T19:29:01.218+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'python_kubernetes_workflow_v2', 'task-1', 'scheduled__2024-08-25T19:23:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/***-dags/testedag.py', '--cfg-path', '/tmp/tmp3jmpo9c8']
[2024-08-25T19:29:01.220+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask task-1
[2024-08-25T19:29:01.449+0000] {task_command.py:426} INFO - Running <TaskInstance: python_kubernetes_workflow_v2.task-1 scheduled__2024-08-25T19:23:00+00:00 [running]> on host c30f0c2d1bf9
[2024-08-25T19:29:01.535+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_kubernetes_workflow_v2' AIRFLOW_CTX_TASK_ID='task-1' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T19:23:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T19:23:00+00:00'
[2024-08-25T19:29:01.535+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-25T19:29:01.538+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/cncf/kubernetes/operators/pod.py:1038 AirflowProviderDeprecationWarning: This function is deprecated. Please use `add_unique_suffix`.
[2024-08-25T19:29:01.538+0000] {pod.py:1057} INFO - Building pod task-1-cth6mqdo with labels: {'dag_id': 'python_kubernetes_workflow_v2', 'task_id': 'task-1', 'run_id': 'scheduled__2024-08-25T1923000000-34b66699b', 'kubernetes_pod_operator': 'True', 'try_number': '2'}
[2024-08-25T19:29:01.551+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-25T19:29:01.551+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 255, in _get_default_client
    config.load_incluster_config(client_configuration=self.client_configuration)
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 570, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 576, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1066, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 271, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 279, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 247, in get_conn
    return self._get_default_client(cluster_context=cluster_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 260, in _get_default_client
    config.load_kube_config(
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    loader = _get_kube_config_loader(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 775, in _get_kube_config_loader
    return KubeConfigLoader(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 206, in __init__
    self.set_active_context(active_context)
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 258, in set_active_context
    context_name = self._config['current-context']
                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 625, in __getitem__
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. Expected key current-context in /home/***/.kube/config
[2024-08-25T19:29:01.565+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=python_kubernetes_workflow_v2, task_id=task-1, execution_date=20240825T192300, start_date=20240825T192901, end_date=20240825T192901
[2024-08-25T19:29:01.578+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task task-1 (Invalid kube-config file. Expected key current-context in /home/***/.kube/config; 2112)
[2024-08-25T19:29:01.594+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-25T19:29:01.802+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T19:29:01.805+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
