[2024-08-25T19:30:00.359+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-25T19:30:00.376+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_kubernetes_workflow_v2.task-2 scheduled__2024-08-25T19:29:00+00:00 [queued]>
[2024-08-25T19:30:00.384+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_kubernetes_workflow_v2.task-2 scheduled__2024-08-25T19:29:00+00:00 [queued]>
[2024-08-25T19:30:00.385+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-08-25T19:30:00.398+0000] {taskinstance.py:2327} INFO - Executing <Task(KubernetesPodOperator): task-2> on 2024-08-25 19:29:00+00:00
[2024-08-25T19:30:00.406+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2161) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T19:30:00.407+0000] {standard_task_runner.py:63} INFO - Started process 2163 to run task
[2024-08-25T19:30:00.406+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'python_kubernetes_workflow_v2', 'task-2', 'scheduled__2024-08-25T19:29:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/***-dags/testedag.py', '--cfg-path', '/tmp/tmpi1dku9wy']
[2024-08-25T19:30:00.408+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask task-2
[2024-08-25T19:30:00.587+0000] {task_command.py:426} INFO - Running <TaskInstance: python_kubernetes_workflow_v2.task-2 scheduled__2024-08-25T19:29:00+00:00 [running]> on host c30f0c2d1bf9
[2024-08-25T19:30:00.678+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_kubernetes_workflow_v2' AIRFLOW_CTX_TASK_ID='task-2' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T19:29:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T19:29:00+00:00'
[2024-08-25T19:30:00.679+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-25T19:30:00.681+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/cncf/kubernetes/operators/pod.py:1038 AirflowProviderDeprecationWarning: This function is deprecated. Please use `add_unique_suffix`.
[2024-08-25T19:30:00.682+0000] {pod.py:1057} INFO - Building pod task-2-aie7pc9x with labels: {'dag_id': 'python_kubernetes_workflow_v2', 'task_id': 'task-2', 'run_id': 'scheduled__2024-08-25T1929000000-4c04144f1', 'kubernetes_pod_operator': 'True', 'try_number': '1'}
[2024-08-25T19:30:02.066+0000] {pod_manager.py:329} ERROR - Exception when attempting to create Namespaced Pod: {   "apiVersion": "v1",   "kind": "Pod",   "metadata": {     "annotations": {},     "labels": {       "foo": "bar",       "dag_id": "python_kubernetes_workflow_v2",       "task_id": "task-2",       "run_id": "scheduled__2024-08-25T1929000000-4c04144f1",       "kubernetes_pod_operator": "True",       "try_number": "1",       "***_version": "2.9.0",       "***_kpo_in_cluster": "False"     },     "name": "task-2-aie7pc9x",     "namespace": "***"   },   "spec": {     "affinity": {},     "containers": [       {         "args": [],         "command": [           "python",           "-c",           "print('hello task 2 ..................')"         ],         "env": [],         "envFrom": [],         "image": "python:3.7",         "imagePullPolicy": "Always",         "name": "base",         "ports": [],         "terminationMessagePolicy": "File",         "volumeMounts": []       }     ],     "hostNetwork": false,     "imagePullSecrets": [],     "initContainers": [],     "nodeSelector": {},     "restartPolicy": "Never",     "securityContext": {},     "tolerations": [],     "volumes": []   } }
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 324, in run_pod_async
    resp = self._client.create_namespaced_pod(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api/core_v1_api.py", line 7356, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api/core_v1_api.py", line 7455, in create_namespaced_pod_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/rest.py", line 279, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'd253eaed-23c8-416e-ad91-9af8b218dd13', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '97cf6122-feaf-40a5-9513-9bce200a5544', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'acff3bde-7ff7-442a-8f20-2d0634e9465a', 'Date': 'Sun, 25 Aug 2024 19:30:01 GMT', 'Content-Length': '194'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"airflow\" not found","reason":"NotFound","details":{"name":"airflow","kind":"namespaces"},"code":404}


[2024-08-25T19:30:02.073+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-25T19:30:02.073+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 570, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 578, in execute_sync
    self.pod = self.get_or_create_pod(  # must set `self.pod` for `on_kill`
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 538, in get_or_create_pod
    self.pod_manager.create_pod(pod=pod_request_obj)
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.12/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 354, in create_pod
    return self.run_pod_async(pod)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 332, in run_pod_async
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/utils/pod_manager.py", line 324, in run_pod_async
    resp = self._client.create_namespaced_pod(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api/core_v1_api.py", line 7356, in create_namespaced_pod
    return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api/core_v1_api.py", line 7455, in create_namespaced_pod_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py", line 391, in request
    return self.rest_client.POST(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/rest.py", line 279, in POST
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'd253eaed-23c8-416e-ad91-9af8b218dd13', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '97cf6122-feaf-40a5-9513-9bce200a5544', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'acff3bde-7ff7-442a-8f20-2d0634e9465a', 'Date': 'Sun, 25 Aug 2024 19:30:01 GMT', 'Content-Length': '194'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"airflow\" not found","reason":"NotFound","details":{"name":"airflow","kind":"namespaces"},"code":404}


[2024-08-25T19:30:02.084+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=python_kubernetes_workflow_v2, task_id=task-2, execution_date=20240825T192900, start_date=20240825T193000, end_date=20240825T193002
[2024-08-25T19:30:02.112+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 98 for task task-2 ((404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'd253eaed-23c8-416e-ad91-9af8b218dd13', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '97cf6122-feaf-40a5-9513-9bce200a5544', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'acff3bde-7ff7-442a-8f20-2d0634e9465a', 'Date': 'Sun, 25 Aug 2024 19:30:01 GMT', 'Content-Length': '194'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"airflow\" not found","reason":"NotFound","details":{"name":"airflow","kind":"namespaces"},"code":404}

; 2163)
[2024-08-25T19:30:02.148+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-25T19:30:02.341+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T19:30:02.343+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
