[2024-07-23T18:27:03.132+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:27:03.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:27:03.134+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:27:03.134+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:27:04.192+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:27:04.190+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:27:04.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:27:04.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.134 seconds
[2024-07-23T18:27:34.292+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:27:34.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:27:34.298+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:27:34.298+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:27:35.331+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:27:35.330+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:27:35.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:27:35.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.089 seconds
[2024-07-23T18:28:05.883+0000] {processor.py:161} INFO - Started process (PID=234) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:28:05.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:28:05.891+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:28:05.890+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:28:06.929+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:28:06.925+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:28:06.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:28:06.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.105 seconds
[2024-07-23T18:28:37.154+0000] {processor.py:161} INFO - Started process (PID=252) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:28:37.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:28:37.160+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:28:37.160+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:28:38.193+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:28:38.191+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:28:38.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:28:38.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.094 seconds
[2024-07-23T18:29:08.419+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:29:08.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:29:08.426+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:29:08.426+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:29:09.466+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:29:09.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:29:09.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:29:09.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.105 seconds
[2024-07-23T18:29:39.693+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:29:39.698+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:29:39.699+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:29:39.699+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:29:40.733+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:29:40.730+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:29:40.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:29:40.781+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.094 seconds
[2024-07-23T18:30:10.987+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:30:10.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:30:10.994+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:30:10.994+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:30:12.029+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:30:12.026+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:30:12.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:30:12.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.134 seconds
[2024-07-23T18:30:42.290+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:30:42.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:30:42.293+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:30:42.293+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:30:43.328+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:30:43.326+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:30:43.387+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:30:43.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.117 seconds
[2024-07-23T18:31:13.621+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:31:13.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:31:13.624+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:31:13.623+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:31:14.659+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:31:14.655+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:31:14.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:31:14.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.089 seconds
[2024-07-23T18:31:44.880+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:31:44.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:31:44.882+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:31:44.882+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:31:45.917+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:31:45.913+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:31:45.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:31:45.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.092 seconds
[2024-07-23T18:32:16.168+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:32:16.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:32:16.174+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:32:16.174+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:32:17.208+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:32:17.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:32:17.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:32:17.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.095 seconds
[2024-07-23T18:32:47.435+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:32:47.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:32:47.441+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:32:47.441+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:32:48.479+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:32:48.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:32:48.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:32:48.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.097 seconds
[2024-07-23T18:33:18.716+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:33:18.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:33:18.723+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:33:18.723+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:33:19.759+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:33:19.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:33:19.785+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:33:19.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.094 seconds
[2024-07-23T18:33:49.984+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:33:49.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:33:49.990+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:33:49.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:33:51.026+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:33:51.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:33:51.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:33:51.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.098 seconds
[2024-07-23T18:34:21.274+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:34:21.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:34:21.277+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:34:21.277+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:34:22.317+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:34:22.314+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:34:22.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:34:22.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.095 seconds
[2024-07-23T18:34:52.539+0000] {processor.py:161} INFO - Started process (PID=474) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:34:52.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:34:52.541+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:34:52.541+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:34:53.596+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:34:53.594+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:34:53.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:34:53.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.118 seconds
[2024-07-23T18:35:23.850+0000] {processor.py:161} INFO - Started process (PID=492) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:35:23.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:35:23.856+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:35:23.856+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:35:24.892+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:35:24.889+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:35:24.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:35:24.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.098 seconds
[2024-07-23T18:35:55.140+0000] {processor.py:161} INFO - Started process (PID=510) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:35:55.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:35:55.148+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:35:55.148+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:35:56.201+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:35:56.197+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:35:56.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:35:56.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.120 seconds
[2024-07-23T18:36:26.410+0000] {processor.py:161} INFO - Started process (PID=528) to work on /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:36:26.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow-dags/datalake/etl_products.py for tasks to queue
[2024-07-23T18:36:26.416+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:36:26.416+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:36:27.453+0000] {logging_mixin.py:188} INFO - [2024-07-23T18:36:27.449+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/airflow-dags/datalake/etl_products.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow-dags/datalake/etl_products.py", line 25, in <module>
    driver = webdriver.Chrome(executable_path=r'/opt/airflow/chromedriver', options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service /opt/airflow/chromedriver unexpectedly exited. Status code was: 127
[2024-07-23T18:36:27.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow-dags/datalake/etl_products.py
[2024-07-23T18:36:27.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow-dags/datalake/etl_products.py took 1.093 seconds
