[2024-05-06T19:05:58.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T19:05:58.513+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_validation_dag_v2.validate_records__1 scheduled__2024-05-06T18:01:00+00:00 [queued]>
[2024-05-06T19:05:58.522+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_validation_dag_v2.validate_records__1 scheduled__2024-05-06T18:01:00+00:00 [queued]>
[2024-05-06T19:05:58.542+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-06T19:05:58.832+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): validate_records__1> on 2024-05-06 18:01:00+00:00
[2024-05-06T19:05:58.841+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_validation_dag_v2', 'validate_records__1', 'scheduled__2024-05-06T18:01:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/***-dags/datalake/data_validation_dag.py', '--cfg-path', '/tmp/tmpe0gp2ec8']
[2024-05-06T19:05:58.844+0000] {standard_task_runner.py:91} INFO - Job 202: Subtask validate_records__1
[2024-05-06T19:05:58.845+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=189) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-06T19:05:58.847+0000] {standard_task_runner.py:63} INFO - Started process 194 to run task
[2024-05-06T19:05:59.033+0000] {task_command.py:426} INFO - Running <TaskInstance: data_validation_dag_v2.validate_records__1 scheduled__2024-05-06T18:01:00+00:00 [running]> on host da062ce1c016
[2024-05-06T19:05:59.639+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='data_validation_dag_v2' AIRFLOW_CTX_TASK_ID='validate_records__1' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T18:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-06T18:01:00+00:00'
[2024-05-06T19:05:59.640+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T19:05:59.640+0000] {logging_mixin.py:188} INFO - Record count is invalid.
[2024-05-06T19:05:59.641+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-06T19:05:59.642+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T19:05:59.656+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=data_validation_dag_v2, task_id=validate_records__1, execution_date=20240506T180100, start_date=20240506T190558, end_date=20240506T190559
[2024-05-06T19:05:59.784+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-06T19:05:59.806+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T19:05:59.927+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
