[2024-08-25T19:16:01.760+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-25T19:16:01.777+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_kubernetes_workflow_v2.task-1 scheduled__2024-08-25T19:10:00+00:00 [queued]>
[2024-08-25T19:16:01.784+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_kubernetes_workflow_v2.task-1 scheduled__2024-08-25T19:10:00+00:00 [queued]>
[2024-08-25T19:16:01.785+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-08-25T19:16:01.797+0000] {taskinstance.py:2327} INFO - Executing <Task(KubernetesPodOperator): task-1> on 2024-08-25 19:10:00+00:00
[2024-08-25T19:16:01.805+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1425) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T19:16:01.806+0000] {standard_task_runner.py:63} INFO - Started process 1427 to run task
[2024-08-25T19:16:01.805+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'python_kubernetes_workflow_v2', 'task-1', 'scheduled__2024-08-25T19:10:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/***-dags/testedag.py', '--cfg-path', '/tmp/tmp9m3ykze3']
[2024-08-25T19:16:01.807+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask task-1
[2024-08-25T19:16:01.986+0000] {task_command.py:426} INFO - Running <TaskInstance: python_kubernetes_workflow_v2.task-1 scheduled__2024-08-25T19:10:00+00:00 [running]> on host c30f0c2d1bf9
[2024-08-25T19:16:02.072+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_kubernetes_workflow_v2' AIRFLOW_CTX_TASK_ID='task-1' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T19:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T19:10:00+00:00'
[2024-08-25T19:16:02.073+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-25T19:16:02.075+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/cncf/kubernetes/operators/pod.py:1038 AirflowProviderDeprecationWarning: This function is deprecated. Please use `add_unique_suffix`.
[2024-08-25T19:16:02.076+0000] {pod.py:1057} INFO - Building pod task-1-ensbm7s5 with labels: {'dag_id': 'python_kubernetes_workflow_v2', 'task_id': 'task-1', 'run_id': 'scheduled__2024-08-25T1910000000-47758fd8a', 'kubernetes_pod_operator': 'True', 'try_number': '2'}
[2024-08-25T19:16:02.085+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-25T19:16:02.086+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 255, in _get_default_client
    config.load_incluster_config(client_configuration=self.client_configuration)
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 121, in load_incluster_config
    try_refresh_token=try_refresh_token).load_and_set(client_configuration)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 54, in load_and_set
    self._load_config()
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/incluster_config.py", line 62, in _load_config
    raise ConfigException("Service host/port is not set.")
kubernetes.config.config_exception.ConfigException: Service host/port is not set.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 570, in execute
    return self.execute_sync(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 576, in execute_sync
    self.pod_request_obj = self.build_pod_request_obj(context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py", line 1066, in build_pod_request_obj
    "airflow_kpo_in_cluster": str(self.hook.is_in_cluster),
                                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 271, in is_in_cluster
    self.api_client  # so we can determine if we are in_cluster or not
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 279, in api_client
    return self.get_conn()
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 247, in get_conn
    return self._get_default_client(cluster_context=cluster_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/hooks/kubernetes.py", line 260, in _get_default_client
    config.load_kube_config(
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    loader = _get_kube_config_loader(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 767, in _get_kube_config_loader
    kcfg = KubeConfigMerger(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 686, in __init__
    self._load_config_from_file_path(paths)
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 711, in _load_config_from_file_path
    self.load_config(path)
  File "/home/airflow/.local/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 719, in load_config
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config. /home/***/.kube/config file is empty
[2024-08-25T19:16:02.096+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=python_kubernetes_workflow_v2, task_id=task-1, execution_date=20240825T191000, start_date=20240825T191601, end_date=20240825T191602
[2024-08-25T19:16:02.105+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task task-1 (Invalid kube-config. /home/***/.kube/config file is empty; 1427)
[2024-08-25T19:16:02.140+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-25T19:16:02.299+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T19:16:02.302+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
